package no.ntnu.noahsprogark.bedpresbingo;

public enum BingoWords {

	KVINNEANDEL, SOSIALT, INTERNKURSING, INTERNASJONALT, UNGT_MILJØ, INTERNSHIP, SOMMERJOBB, ABAKUS, DATATEKNIKK, INDØK, JAVA, DOTNET, FLAT_STRUKTUR, INNOVATIVT, SKREDDERSYDDE_LØSNINGER, SKYTJENESTER, FAGDAG, PROGRAMMERING, OFFENTLIGE_KUNDER, NAV, OMSETNING, RÅDGIVNING, TEKNOLOGI;
	
}
